exports.CANON80D = [
  '#canon_official',
  '#canon_photos',
  '#canoncamera',
  '#canoncollective',
  '#canonfanphoto',
  '#canonfeed',
  '#canonglobal',
  '#canonlens',
  '#canonlife',
  '#canonphoto',
  '#canonphotographer',
  '#canonphotographers',
  '#canonphotography',
  '#canonphotos',
  '#canonshot',
  '#mycanon',
  '#teamcanon'
]
