name: Test PR
on:
    pull_request:
        branches:
            - master
            - develop

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            - name: NPM Version
              run: npm --version

            - name: Install Dependencies
              run: npm ci

            - name: Test
              run: npm test
